app = "llm-feedback-assistant"
primary_region = "ams"
[build]
  dockerfile = "docker/Dockerfile"
[[services]]
  internal_port = 8080
  protocol = "tcp"
  [[services.ports]]
    port = "80"
    handlers = ["http"]