// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zuefodkzlhlqqlmjkqnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1ZWZvZGt6bGhscXFsbWprcW5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3OTMxOTksImV4cCI6MjA2MjM2OTE5OX0.BMv9q0fz1Pm2cuu8iJ36Tjqj6KSjADShYkfZ1BR2tOg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);